import 'dart:collection';
import 'dart:convert';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

import '../../../core/project/generated_dart_path.dart';
import 'immutable_bytes.dart';
import 'l10n_evidence_failure.dart';
import 'l10n_family_snapshot.dart';
import 'l10n_generator.dart';
import 'l10n_stage_inventory.dart';

const _reconciliationStage = 'output-reconciliation';
const _fingerprintSchema = 'l10n-witnessed-change-set-v1';

/// Paths whose generation-time behavior has been proven before launch.
final class L10nGenerationAllowlist {
  /// Creates an immutable, canonical generation allowlist.
  L10nGenerationAllowlist({
    required Set<String> replacementOutputPaths,
    required this.untranslatedSidecarPath,
    required Set<String> provenUnrelatedSiblingPaths,
  }) : replacementOutputPaths = _sortedPathSet(
         replacementOutputPaths,
         name: 'replacementOutputPaths',
         requireNonEmpty: true,
       ),
       provenUnrelatedSiblingPaths = _sortedPathSet(
         provenUnrelatedSiblingPaths,
         name: 'provenUnrelatedSiblingPaths',
       ) {
    final sidecar = untranslatedSidecarPath;
    if (sidecar != null && !_isSafeRelativePosixPath(sidecar)) {
      throw ArgumentError.value(sidecar, 'untranslatedSidecarPath');
    }

    final owners = <String, String>{};
    void claim(String path) {
      final folded = _asciiFold(path);
      final previous = owners[folded];
      if (previous != null) {
        throw ArgumentError(
          'Generation allowlist paths overlap or case-fold collide: '
          '$previous and $path.',
        );
      }
      owners[folded] = path;
    }

    for (final path in this.replacementOutputPaths) {
      claim(path);
    }
    if (sidecar != null) claim(sidecar);
    for (final path in this.provenUnrelatedSiblingPaths) {
      claim(path);
    }
    _validateNonAliasingPaths(owners.values, 'generation allowlist');
  }

  /// Required generated Dart files that may be replaced.
  final Set<String> replacementOutputPaths;

  /// Optional untranslated-message report that may be replaced.
  final String? untranslatedSidecarPath;

  /// Output-directory siblings that must remain exactly unchanged.
  final Set<String> provenUnrelatedSiblingPaths;
}

/// One byte- and mode-exact file replacement.
final class L10nFileReplacement {
  /// Creates an immutable replacement of one existing regular file.
  L10nFileReplacement({
    required this.relativePath,
    required ImmutableBytes beforeBytes,
    required ImmutableBytes afterBytes,
    required this.beforeMode,
    required this.afterMode,
  }) : beforeBytes = ImmutableBytes.copyOf(beforeBytes.copy()),
       afterBytes = ImmutableBytes.copyOf(afterBytes.copy()) {
    if (!_isSafeRelativePosixPath(relativePath)) {
      throw ArgumentError.value(relativePath, 'relativePath');
    }
    _validateMode(beforeMode, 'beforeMode');
    _validateMode(afterMode, 'afterMode');
    if (beforeMode != afterMode) {
      throw ArgumentError('A Stage 1 replacement may not change file mode.');
    }
    if (this.beforeBytes.contentEquals(this.afterBytes)) {
      throw ArgumentError('A replacement must change exact file bytes.');
    }
  }

  /// Canonical project-relative POSIX path.
  final String relativePath;

  /// Reproduced live bytes.
  final ImmutableBytes beforeBytes;

  /// Candidate generated bytes.
  final ImmutableBytes afterBytes;

  /// Reproduced live POSIX permission bits, or null off POSIX.
  final int? beforeMode;

  /// Candidate POSIX permission bits, or null off POSIX.
  final int? afterMode;
}

/// Complete immutable source-to-candidate replacement evidence.
final class L10nWitnessedChangeSet {
  /// Creates a deeply copied, deterministically ordered change set.
  L10nWitnessedChangeSet({
    required Map<String, L10nFileReplacement> arbReplacements,
    required Map<String, L10nFileReplacement> generatedReplacements,
  }) : arbReplacements = _copyReplacementMap(
         arbReplacements,
         name: 'arbReplacements',
       ),
       generatedReplacements = _copyReplacementMap(
         generatedReplacements,
         name: 'generatedReplacements',
       ) {
    final overlap = this.arbReplacements.keys.toSet().intersection(
      this.generatedReplacements.keys.toSet(),
    );
    if (overlap.isNotEmpty) {
      throw ArgumentError('ARB and generated replacement paths overlap.');
    }
    _validateNonAliasingPaths(<String>{
      ...this.arbReplacements.keys,
      ...this.generatedReplacements.keys,
    }, 'witnessed change set');
    fingerprint = _changeSetFingerprint(
      this.arbReplacements,
      this.generatedReplacements,
    );
  }

  /// Exact live-to-planned ARB replacements.
  final Map<String, L10nFileReplacement> arbReplacements;

  /// Exact baseline-to-candidate generated replacements.
  final Map<String, L10nFileReplacement> generatedReplacements;

  /// Root- and invocation-independent SHA-256 identity.
  late final String fingerprint;
}

/// Result of reconciling independent baseline and candidate generation runs.
sealed class L10nReconciliationResult {
  const L10nReconciliationResult();
}

/// Reconciliation produced one publishable, witnessed change set.
final class L10nReconciliationReady extends L10nReconciliationResult {
  /// Creates an accepted reconciliation result.
  const L10nReconciliationReady(this.changeSet);

  /// Immutable byte- and mode-exact replacements.
  final L10nWitnessedChangeSet changeSet;
}

/// Reconciliation rejected without producing a change set.
final class L10nReconciliationRejected extends L10nReconciliationResult {
  /// Creates a sorted, duplicate-free, immutable rejection.
  L10nReconciliationRejected(Iterable<L10nEvidenceFailure> failures)
    : failures = _sortedFailures(failures) {
    if (this.failures.isEmpty) {
      throw ArgumentError('A rejected reconciliation requires a failure.');
    }
  }

  /// Stable reasons why no change set may be published.
  final List<L10nEvidenceFailure> failures;
}

/// Reconciles generator filesystem evidence without touching the filesystem.
abstract interface class L10nOutputReconciler {
  /// Reproduces live output and derives only the candidate delta.
  L10nReconciliationResult reconcile({
    required L10nFamilySnapshot liveSnapshot,
    required L10nGenerationAllowlist allowlist,
    required L10nGenerationRun baseline,
    required L10nGenerationRun candidate,
  });
}

/// Pure fail-closed implementation of staged l10n output reconciliation.
final class DefaultL10nOutputReconciler implements L10nOutputReconciler {
  /// Creates the stateless reconciler.
  const DefaultL10nOutputReconciler();

  @override
  L10nReconciliationResult reconcile({
    required L10nFamilySnapshot liveSnapshot,
    required L10nGenerationAllowlist allowlist,
    required L10nGenerationRun baseline,
    required L10nGenerationRun candidate,
  }) {
    final allowlistFailure = _validateAllowlist(liveSnapshot, allowlist);
    if (allowlistFailure != null) return _rejected([allowlistFailure]);

    final phaseFailures = <L10nEvidenceFailure>[
      if (baseline.phase != L10nGenerationPhase.baseline)
        _failure(
          L10nEvidenceRejectionCode.baselineGenerationFailed,
          'generation-phase-mismatch',
        ),
      if (candidate.phase != L10nGenerationPhase.candidate)
        _failure(
          L10nEvidenceRejectionCode.candidateGenerationFailed,
          'generation-phase-mismatch',
        ),
    ];
    if (phaseFailures.isNotEmpty) return _rejected(phaseFailures);
    final reportedFailures = <L10nEvidenceFailure>[
      ...baseline.failures,
      ...candidate.failures,
    ];
    if (reportedFailures.isNotEmpty) return _rejected(reportedFailures);
    if (baseline.commandIdentity == candidate.commandIdentity) {
      return _rejected([
        _failure(
          L10nEvidenceRejectionCode.toolchainDrift,
          'generation-command-identity-collision',
        ),
      ]);
    }

    final processFailures = <L10nEvidenceFailure>[
      ..._unreportedProcessFailures(baseline),
      ..._unreportedProcessFailures(candidate),
    ];
    if (processFailures.isNotEmpty) return _rejected(processFailures);

    final managedPaths = <String>{
      ...allowlist.replacementOutputPaths,
      if (allowlist.untranslatedSidecarPath case final path?) path,
    };
    final writeFailures = <L10nEvidenceFailure>[
      ..._inventoryAuthorityFailures(baseline),
      ..._inventoryAuthorityFailures(candidate),
      ..._unexpectedWrites(baseline, managedPaths),
      ..._unexpectedWrites(candidate, managedPaths),
    ];
    if (writeFailures.isNotEmpty) return _rejected(writeFailures);

    final ownershipFailures = _ownershipFailures(
      liveSnapshot,
      allowlist,
      baseline,
      candidate,
    );
    if (ownershipFailures.isNotEmpty) return _rejected(ownershipFailures);

    final prestateFailures = <L10nEvidenceFailure>[
      ..._prestateFailures(liveSnapshot, baseline, candidateArbs: false),
      ..._prestateFailures(liveSnapshot, candidate, candidateArbs: true),
    ];
    if (prestateFailures.isNotEmpty) return _rejected(prestateFailures);

    final reproduced = _reproduceBaseline(
      liveSnapshot,
      allowlist,
      baseline.after,
    );
    if (reproduced.failures.isNotEmpty) {
      return _rejected(reproduced.failures);
    }

    final generated = _candidateReplacements(
      allowlist,
      reproduced.entries,
      candidate.after,
    );
    if (generated.failures.isNotEmpty) return _rejected(generated.failures);

    final arb = _arbReplacements(liveSnapshot);
    if (arb.failures.isNotEmpty) return _rejected(arb.failures);

    return L10nReconciliationReady(
      L10nWitnessedChangeSet(
        arbReplacements: arb.replacements,
        generatedReplacements: generated.replacements,
      ),
    );
  }
}

L10nEvidenceFailure? _validateAllowlist(
  L10nFamilySnapshot snapshot,
  L10nGenerationAllowlist allowlist,
) {
  if (!_sameStrings(
        snapshot.expectedGeneratedPaths,
        allowlist.replacementOutputPaths,
      ) ||
      snapshot.optionalUntranslatedPath != allowlist.untranslatedSidecarPath ||
      !_sameStrings(
        snapshot.provenUnrelatedOutputSiblings,
        allowlist.provenUnrelatedSiblingPaths,
      )) {
    return _failure(
      L10nEvidenceRejectionCode.outputFamilyAmbiguous,
      'generation-allowlist-snapshot-mismatch',
    );
  }
  return null;
}

List<L10nEvidenceFailure> _unreportedProcessFailures(L10nGenerationRun run) {
  final stage = '${run.phase.name}-generation';
  final phaseCode = run.phase == L10nGenerationPhase.baseline
      ? L10nEvidenceRejectionCode.baselineGenerationFailed
      : L10nEvidenceRejectionCode.candidateGenerationFailed;
  final process = run.processResult;
  if (process == null) {
    return [
      _failure(phaseCode, 'generation-process-result-missing', stage: stage),
    ];
  }
  final failures = <L10nEvidenceFailure>[];
  if (process.timedOut) {
    failures.add(
      _failure(phaseCode, 'generation-process-timeout', stage: stage),
    );
  } else if (process.exitCode != 0) {
    failures.add(
      _failure(phaseCode, 'generation-process-nonzero-exit', stage: stage),
    );
  }
  if (process.outputTruncated) {
    failures.add(
      _failure(
        L10nEvidenceRejectionCode.generatorOutputTruncated,
        'generator-output-truncated',
        stage: stage,
      ),
    );
  }
  return failures;
}

List<L10nEvidenceFailure> _unexpectedWrites(
  L10nGenerationRun run,
  Set<String> managedPaths,
) {
  final stage = '${run.phase.name}-generation';
  final parents = <String>{
    for (final path in managedPaths) ..._parentsOf(path),
  };
  final paths = SplayTreeSet<String>.of(run.before.entries.keys)
    ..addAll(run.after.entries.keys)
    ..addAll(run.before.invalidPaths)
    ..addAll(run.after.invalidPaths);
  final failures = <L10nEvidenceFailure>[];
  for (final path in paths) {
    final invalid =
        run.before.invalidPaths.contains(path) ||
        run.after.invalidPaths.contains(path);
    final before = run.before.entries[path];
    final after = run.after.entries[path];
    if (!invalid && _sameEntry(before, after)) continue;
    if (!invalid && managedPaths.contains(path)) continue;
    if (!invalid &&
        parents.contains(path) &&
        before == null &&
        after?.kind == L10nStageEntryKind.directory) {
      continue;
    }
    failures.add(
      _failure(
        L10nEvidenceRejectionCode.unexpectedStageWrite,
        'unexpected-stage-write',
        stage: stage,
        relativePath: path,
      ),
    );
  }
  return failures;
}

List<L10nEvidenceFailure> _inventoryAuthorityFailures(L10nGenerationRun run) {
  final stage = '${run.phase.name}-generation';
  final failures = <L10nEvidenceFailure>[];
  for (final capture in [run.before, run.after]) {
    final folded = <String, String>{};
    for (final entry in capture.entries.entries) {
      final path = entry.key;
      if (!_isSafeRelativePosixPath(path)) {
        failures.add(
          _failure(
            L10nEvidenceRejectionCode.unexpectedStageWrite,
            'unexpected-stage-write',
            stage: stage,
            relativePath: path,
          ),
        );
        continue;
      }
      if (!capture.invalidPaths.contains(path) &&
          !_isAuthoritativeInventoryEntry(entry.value)) {
        failures.add(
          _failure(
            L10nEvidenceRejectionCode.unexpectedStageWrite,
            'inventory-entry-evidence-invalid',
            stage: stage,
            relativePath: path,
          ),
        );
      }
      for (final parent in _parentsOf(path)) {
        if (capture.entries[parent]?.kind != L10nStageEntryKind.directory) {
          failures.add(
            _failure(
              L10nEvidenceRejectionCode.unexpectedStageWrite,
              'inventory-entry-evidence-invalid',
              stage: stage,
              relativePath: path,
            ),
          );
          break;
        }
      }
      final key = _asciiFold(path);
      final previous = folded[key];
      if (previous != null && previous != path) {
        for (final collision in [previous, path]) {
          failures.add(
            _failure(
              L10nEvidenceRejectionCode.unexpectedStageWrite,
              'unexpected-stage-write',
              stage: stage,
              relativePath: collision,
            ),
          );
        }
      } else {
        folded[key] = path;
      }
    }
  }
  return failures;
}

bool _isAuthoritativeInventoryEntry(L10nStageEntry entry) {
  if (entry.kind == L10nStageEntryKind.symbolicLink ||
      entry.kind == L10nStageEntryKind.other) {
    return false;
  }
  if (entry.kind == L10nStageEntryKind.directory) return true;
  final contentHash = entry.sha256;
  if (contentHash == null) return false;
  final captured = entry.capturedBytes;
  return captured == null || captured.sha256Hex == contentHash;
}

List<L10nEvidenceFailure> _prestateFailures(
  L10nFamilySnapshot snapshot,
  L10nGenerationRun run, {
  required bool candidateArbs,
}) {
  final failures = <L10nEvidenceFailure>[];
  final presentPaths = <String>{};
  for (final snapshotEntry in snapshot.entries.values) {
    final path = snapshotEntry.relativePosixPath;
    final actual = run.before.entries[path];
    switch (snapshotEntry.state) {
      case L10nSnapshotAbsent():
        if (actual != null) {
          failures.add(
            _prestateFailure(run.phase, path, isCandidateArb: false),
          );
        }
      case L10nSnapshotPresent(:final stageBytes, :final posixMode):
        presentPaths.add(path);
        final expectedBytes =
            candidateArbs &&
                snapshot.mutationPlan.candidateArbBytes.containsKey(path)
            ? snapshot.mutationPlan.candidateArbBytes[path]!
            : stageBytes;
        if (!_entryMatchesBytes(actual, expectedBytes, posixMode)) {
          failures.add(
            _prestateFailure(
              run.phase,
              path,
              isCandidateArb:
                  candidateArbs &&
                  snapshot.mutationPlan.candidateArbBytes.containsKey(path),
            ),
          );
        }
    }
  }

  final expectedParents = <String>{
    for (final path in presentPaths) ..._parentsOf(path),
  }..removeAll(presentPaths);
  for (final parent in expectedParents) {
    if (run.before.entries[parent]?.kind != L10nStageEntryKind.directory) {
      failures.add(_prestateFailure(run.phase, parent, isCandidateArb: false));
    }
  }

  final expectedPaths = <String>{...presentPaths, ...expectedParents};
  for (final path in run.before.entries.keys) {
    if (expectedPaths.contains(path) || snapshot.entries.containsKey(path)) {
      continue;
    }
    failures.add(
      _failure(
        run.phase == L10nGenerationPhase.baseline
            ? L10nEvidenceRejectionCode.baselineGenerationFailed
            : L10nEvidenceRejectionCode.candidateGenerationFailed,
        '${run.phase.name}-stage-prestate-extra',
        relativePath: path,
      ),
    );
  }
  return failures;
}

L10nEvidenceFailure _prestateFailure(
  L10nGenerationPhase phase,
  String path, {
  required bool isCandidateArb,
}) {
  if (phase == L10nGenerationPhase.candidate && isCandidateArb) {
    return _failure(
      L10nEvidenceRejectionCode.candidateVerificationFailed,
      'candidate-arb-prestate-mismatch',
      relativePath: path,
    );
  }
  return _failure(
    phase == L10nGenerationPhase.baseline
        ? L10nEvidenceRejectionCode.baselineGenerationFailed
        : L10nEvidenceRejectionCode.candidateGenerationFailed,
    '${phase.name}-stage-prestate-mismatch',
    relativePath: path,
  );
}

List<L10nEvidenceFailure> _ownershipFailures(
  L10nFamilySnapshot snapshot,
  L10nGenerationAllowlist allowlist,
  L10nGenerationRun baseline,
  L10nGenerationRun candidate,
) {
  final failures = <L10nEvidenceFailure>[];
  final baseEntries = snapshot.entries.values
      .where((entry) => entry.role == L10nSnapshotRole.generatedBase)
      .toList(growable: false);
  if (baseEntries.length != 1) {
    return [
      _failure(
        L10nEvidenceRejectionCode.outputFamilyAmbiguous,
        'generated-base-authority-missing',
      ),
    ];
  }
  final basePath = baseEntries.single.relativePosixPath;
  final slash = basePath.lastIndexOf('/');
  final directory = slash < 0 ? '' : basePath.substring(0, slash);
  final basename = slash < 0 ? basePath : basePath.substring(slash + 1);
  final dot = basename.indexOf('.');
  if (dot <= 0) {
    return [
      _failure(
        L10nEvidenceRejectionCode.outputFamilyAmbiguous,
        'generated-base-authority-missing',
        relativePath: basePath,
      ),
    ];
  }
  final stem = _asciiFold(basename.substring(0, dot));
  final suffix = _asciiFold(basename.substring(dot));

  L10nEvidenceFailure? classifySibling(
    String path, {
    L10nSnapshotPresent? snapshotState,
  }) {
    final pathSlash = path.lastIndexOf('/');
    final pathDirectory = pathSlash < 0 ? '' : path.substring(0, pathSlash);
    if (pathDirectory != directory) return null;
    if (allowlist.replacementOutputPaths.contains(path) ||
        path == allowlist.untranslatedSidecarPath) {
      return null;
    }
    final name = _asciiFold(
      pathSlash < 0 ? path : path.substring(pathSlash + 1),
    );
    if (name.startsWith('${stem}_') && name.endsWith(suffix)) {
      return _failure(
        L10nEvidenceRejectionCode.outputFamilyAmbiguous,
        'unowned-output-family-sibling',
        relativePath: path,
      );
    }
    if (isGeneratedDartPath(path) ||
        (snapshotState != null &&
            _claimsGeneratedProvenance(snapshotState.sourceBytes))) {
      return _failure(
        L10nEvidenceRejectionCode.outputFamilyAmbiguous,
        'generated-provenance-sibling-unowned',
        relativePath: path,
      );
    }
    if (!allowlist.provenUnrelatedSiblingPaths.contains(path)) {
      return _failure(
        L10nEvidenceRejectionCode.outputFamilyAmbiguous,
        'unowned-output-sibling',
        relativePath: path,
      );
    }
    return null;
  }

  for (final entry in snapshot.entries.values) {
    final path = entry.relativePosixPath;
    final state = entry.state;
    if (state is! L10nSnapshotPresent) continue;
    final failure = classifySibling(path, snapshotState: state);
    if (failure != null) failures.add(failure);
  }

  final captures = [
    baseline.before,
    baseline.after,
    candidate.before,
    candidate.after,
  ];
  final inventoryPaths = SplayTreeSet<String>();
  for (final capture in captures) {
    inventoryPaths.addAll(capture.entries.keys);
  }
  for (final path in inventoryPaths) {
    final observed = <L10nStageEntry>[
      for (final capture in captures)
        if (capture.entries[path] case final entry?) entry,
    ];
    if (observed.every((entry) => entry.kind == L10nStageEntryKind.directory)) {
      continue;
    }
    final snapshotState = snapshot.entries[path]?.state;
    final failure = classifySibling(
      path,
      snapshotState: snapshotState is L10nSnapshotPresent
          ? snapshotState
          : null,
    );
    if (failure != null) failures.add(failure);
  }

  for (final path in allowlist.provenUnrelatedSiblingPaths) {
    final snapshotEntry = snapshot.entries[path];
    final state = snapshotEntry?.state;
    if (state is! L10nSnapshotPresent) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.outputFamilyAmbiguous,
          'proven-output-sibling-authority-missing',
          relativePath: path,
        ),
      );
      continue;
    }
    if (isGeneratedDartPath(path) ||
        _claimsGeneratedProvenance(state.sourceBytes)) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.outputFamilyAmbiguous,
          'generated-provenance-sibling-unowned',
          relativePath: path,
        ),
      );
      continue;
    }
    final states = <L10nStageEntry?>[
      baseline.before.entries[path],
      baseline.after.entries[path],
      candidate.before.entries[path],
      candidate.after.entries[path],
    ];
    if (states.any(
      (entry) => !_entryMatchesBytes(entry, state.sourceBytes, state.posixMode),
    )) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.outputFamilyAmbiguous,
          'proven-output-sibling-mismatch',
          relativePath: path,
        ),
      );
    }
  }
  return failures;
}

bool _claimsGeneratedProvenance(ImmutableBytes bytes) {
  final source = bytes.copy();
  final hasBom =
      source.length >= 3 &&
      source[0] == 0xef &&
      source[1] == 0xbb &&
      source[2] == 0xbf;
  final start = hasBom ? 3 : 0;
  final remaining = source.length - start;
  final prefixLength = remaining < 1024 ? remaining : 1024;
  final prefix = String.fromCharCodes(source.skip(start).take(prefixLength));
  final prologue = StringBuffer();
  var inBlockComment = false;
  for (final rawLine in const LineSplitter().convert(prefix)) {
    final line = rawLine.trimLeft();
    if (line.isEmpty) continue;
    if (inBlockComment) {
      prologue.writeln(line);
      if (line.contains('*/')) inBlockComment = false;
      continue;
    }
    if (line.startsWith('//')) {
      prologue.writeln(line.substring(2));
      continue;
    }
    if (line.startsWith('/*')) {
      prologue.writeln(line.substring(2));
      inBlockComment = !line.contains('*/');
      continue;
    }
    break;
  }

  final claim = prologue.toString().toLowerCase();
  if (claim.contains('@generated')) return true;
  if (!RegExp(r'\bgenerated\b').hasMatch(claim)) return false;
  return RegExp(
        r'\b(?:generated\s+(?:code|by|via|from|automatically)|'
        r'code\s+generated|auto-generated)\b',
      ).hasMatch(claim) ||
      RegExp(r'\bdo\s+not\s+(?:edit|modify)\b').hasMatch(claim);
}

_ReproducedOutputs _reproduceBaseline(
  L10nFamilySnapshot snapshot,
  L10nGenerationAllowlist allowlist,
  L10nStageInventoryCapture baselineAfter,
) {
  final reproduced = SplayTreeMap<String, L10nStageEntry>();
  final failures = <L10nEvidenceFailure>[];
  for (final path in allowlist.replacementOutputPaths) {
    final state = snapshot.entries[path]?.state;
    final actual = baselineAfter.entries[path];
    if (state is! L10nSnapshotPresent ||
        !_entryMatchesCapturedBytes(
          actual,
          state.sourceBytes,
          state.posixMode,
        )) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.staleGeneratedOutput,
          'baseline-output-mismatch',
          relativePath: path,
        ),
      );
      continue;
    }
    reproduced[path] = actual!;
  }

  final sidecar = allowlist.untranslatedSidecarPath;
  if (sidecar != null) {
    final state = snapshot.entries[sidecar]?.state;
    final actual = baselineAfter.entries[sidecar];
    if (state is L10nSnapshotAbsent && actual == null) {
      // The optional sidecar alone may reproduce explicit absence.
    } else if (state is L10nSnapshotPresent &&
        _entryMatchesCapturedBytes(
          actual,
          state.sourceBytes,
          state.posixMode,
        )) {
      reproduced[sidecar] = actual!;
    } else {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.staleGeneratedOutput,
          'baseline-output-mismatch',
          relativePath: sidecar,
        ),
      );
    }
  }
  return _ReproducedOutputs(reproduced, failures);
}

_ReplacementResult _candidateReplacements(
  L10nGenerationAllowlist allowlist,
  Map<String, L10nStageEntry> reproduced,
  L10nStageInventoryCapture candidateAfter,
) {
  final replacements = SplayTreeMap<String, L10nFileReplacement>();
  final failures = <L10nEvidenceFailure>[];
  final managed = <String>{
    ...allowlist.replacementOutputPaths,
    if (allowlist.untranslatedSidecarPath case final path?) path,
  };
  for (final path in SplayTreeSet<String>.of(managed)) {
    final baseline = reproduced[path];
    final candidate = candidateAfter.entries[path];
    if ((baseline == null) != (candidate == null) ||
        (baseline != null && candidate?.kind != baseline.kind)) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.outputFamilyAmbiguous,
          'candidate-output-shape-changed',
          relativePath: path,
        ),
      );
      continue;
    }
    if (baseline == null) continue;
    if (candidate!.posixMode != baseline.posixMode) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.candidateGenerationFailed,
          'candidate-output-mode-mismatch',
          relativePath: path,
        ),
      );
      continue;
    }
    final beforeBytes = _authoritativeCapturedBytes(baseline);
    final afterBytes = _authoritativeCapturedBytes(candidate);
    if (beforeBytes == null || afterBytes == null) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.candidateGenerationFailed,
          'candidate-output-evidence-incomplete',
          relativePath: path,
        ),
      );
      continue;
    }
    if (!beforeBytes.contentEquals(afterBytes)) {
      replacements[path] = L10nFileReplacement(
        relativePath: path,
        beforeBytes: beforeBytes,
        afterBytes: afterBytes,
        beforeMode: baseline.posixMode,
        afterMode: candidate.posixMode,
      );
    }
  }
  return _ReplacementResult(replacements, failures);
}

_ReplacementResult _arbReplacements(L10nFamilySnapshot snapshot) {
  final replacements = SplayTreeMap<String, L10nFileReplacement>();
  final failures = <L10nEvidenceFailure>[];
  for (final planned in snapshot.mutationPlan.candidateArbBytes.entries) {
    final path = planned.key;
    final state = snapshot.entries[path]?.state;
    if (state is! L10nSnapshotPresent) {
      failures.add(
        _failure(
          L10nEvidenceRejectionCode.candidateVerificationFailed,
          'candidate-arb-authority-missing',
          relativePath: path,
        ),
      );
      continue;
    }
    if (!state.sourceBytes.contentEquals(planned.value)) {
      replacements[path] = L10nFileReplacement(
        relativePath: path,
        beforeBytes: state.sourceBytes,
        afterBytes: planned.value,
        beforeMode: state.posixMode,
        afterMode: state.posixMode,
      );
    }
  }
  return _ReplacementResult(replacements, failures);
}

final class _ReproducedOutputs {
  const _ReproducedOutputs(this.entries, this.failures);

  final Map<String, L10nStageEntry> entries;
  final List<L10nEvidenceFailure> failures;
}

final class _ReplacementResult {
  const _ReplacementResult(this.replacements, this.failures);

  final Map<String, L10nFileReplacement> replacements;
  final List<L10nEvidenceFailure> failures;
}

bool _entryMatchesBytes(
  L10nStageEntry? entry,
  ImmutableBytes expected,
  int? expectedMode,
) =>
    entry != null &&
    entry.kind == L10nStageEntryKind.regularFile &&
    entry.sha256 == expected.sha256Hex &&
    entry.posixMode == expectedMode;

bool _entryMatchesCapturedBytes(
  L10nStageEntry? entry,
  ImmutableBytes expected,
  int? expectedMode,
) =>
    _entryMatchesBytes(entry, expected, expectedMode) &&
    _authoritativeCapturedBytes(entry!)?.contentEquals(expected) == true;

ImmutableBytes? _authoritativeCapturedBytes(L10nStageEntry entry) {
  if (entry.kind != L10nStageEntryKind.regularFile ||
      entry.sha256 == null ||
      entry.capturedBytes == null ||
      entry.capturedBytes!.sha256Hex != entry.sha256) {
    return null;
  }
  return ImmutableBytes.copyOf(entry.capturedBytes!.copy());
}

bool _sameEntry(L10nStageEntry? left, L10nStageEntry? right) =>
    identical(left, right) ||
    (left != null &&
        right != null &&
        left.kind == right.kind &&
        left.sha256 == right.sha256 &&
        left.posixMode == right.posixMode);

Iterable<String> _parentsOf(String path) sync* {
  final segments = path.split('/');
  for (var length = 1; length < segments.length; length++) {
    yield segments.take(length).join('/');
  }
}

Map<String, L10nFileReplacement> _copyReplacementMap(
  Map<String, L10nFileReplacement> source, {
  required String name,
}) {
  final result = SplayTreeMap<String, L10nFileReplacement>();
  final folded = <String, String>{};
  for (final entry in source.entries) {
    if (entry.key != entry.value.relativePath ||
        !_isSafeRelativePosixPath(entry.key)) {
      throw ArgumentError('$name contains a key/path mismatch.');
    }
    final previous = folded[_asciiFold(entry.key)];
    if (previous != null && previous != entry.key) {
      throw ArgumentError('$name contains a case-fold collision.');
    }
    folded[_asciiFold(entry.key)] = entry.key;
    final replacement = entry.value;
    result[entry.key] = L10nFileReplacement(
      relativePath: replacement.relativePath,
      beforeBytes: replacement.beforeBytes,
      afterBytes: replacement.afterBytes,
      beforeMode: replacement.beforeMode,
      afterMode: replacement.afterMode,
    );
  }
  return UnmodifiableMapView(result);
}

String _changeSetFingerprint(
  Map<String, L10nFileReplacement> arbs,
  Map<String, L10nFileReplacement> generated,
) {
  final writer = _FingerprintWriter()..addString(_fingerprintSchema);
  void addMap(String role, Map<String, L10nFileReplacement> replacements) {
    writer
      ..addString(role)
      ..addInt(replacements.length);
    for (final replacement in replacements.values) {
      writer
        ..addString(replacement.relativePath)
        ..addInt(replacement.beforeBytes.length)
        ..addString(replacement.beforeBytes.sha256Hex)
        ..addNullableInt(replacement.beforeMode)
        ..addInt(replacement.afterBytes.length)
        ..addString(replacement.afterBytes.sha256Hex)
        ..addNullableInt(replacement.afterMode);
    }
  }

  addMap('arb', arbs);
  addMap('generated', generated);
  return writer.finish();
}

final class _FingerprintWriter {
  final BytesBuilder _bytes = BytesBuilder(copy: false);

  void addString(String value) {
    final encoded = utf8.encode(value);
    addInt(encoded.length);
    _bytes.add(encoded);
  }

  void addInt(int value) => addStringWithoutLength(value.toString());

  void addNullableInt(int? value) =>
      addStringWithoutLength(value?.toString() ?? 'null');

  void addStringWithoutLength(String value) {
    final encoded = utf8.encode(value);
    final length = ByteData(8)..setUint64(0, encoded.length);
    _bytes
      ..add(length.buffer.asUint8List())
      ..add(encoded);
  }

  String finish() => sha256.convert(_bytes.takeBytes()).toString();
}

Set<String> _sortedPathSet(
  Iterable<String> source, {
  required String name,
  bool requireNonEmpty = false,
}) {
  final result = SplayTreeSet<String>();
  final folded = <String, String>{};
  for (final path in source) {
    if (!_isSafeRelativePosixPath(path)) {
      throw ArgumentError.value(path, name);
    }
    final previous = folded[_asciiFold(path)];
    if (previous != null && previous != path) {
      throw ArgumentError('$name contains a case-fold collision.');
    }
    folded[_asciiFold(path)] = path;
    result.add(path);
  }
  if (requireNonEmpty && result.isEmpty) {
    throw ArgumentError('$name must not be empty.');
  }
  return Set<String>.unmodifiable(result);
}

void _validateNonAliasingPaths(Iterable<String> paths, String name) {
  final folded = paths.map(_asciiFold).toSet().toList()..sort();
  if (folded.length != paths.length) {
    throw ArgumentError('$name contains a case-fold collision.');
  }
  for (var index = 0; index < folded.length; index++) {
    final ancestor = folded[index];
    for (var other = index + 1; other < folded.length; other++) {
      final candidate = folded[other];
      if (candidate.startsWith('$ancestor/')) {
        throw ArgumentError('$name contains an ancestor/leaf alias.');
      }
    }
  }
}

List<L10nEvidenceFailure> _sortedFailures(
  Iterable<L10nEvidenceFailure> source,
) {
  final ordered = source.toList(growable: false)..sort(_compareFailures);
  final deduplicated = <L10nEvidenceFailure>[];
  for (final failure in ordered) {
    if (deduplicated.isEmpty ||
        _compareFailures(deduplicated.last, failure) != 0) {
      deduplicated.add(failure);
    }
  }
  return List<L10nEvidenceFailure>.unmodifiable(deduplicated);
}

int _compareFailures(L10nEvidenceFailure left, L10nEvidenceFailure right) {
  var comparison = left.code.index.compareTo(right.code.index);
  if (comparison != 0) return comparison;
  comparison = left.stage.compareTo(right.stage);
  if (comparison != 0) return comparison;
  comparison = _compareNullable(left.relativePath, right.relativePath);
  if (comparison != 0) return comparison;
  return left.detailCode.compareTo(right.detailCode);
}

int _compareNullable(String? left, String? right) {
  if (left == null) return right == null ? 0 : -1;
  if (right == null) return 1;
  return left.compareTo(right);
}

L10nReconciliationRejected _rejected(Iterable<L10nEvidenceFailure> failures) =>
    L10nReconciliationRejected(failures);

L10nEvidenceFailure _failure(
  L10nEvidenceRejectionCode code,
  String detailCode, {
  String stage = _reconciliationStage,
  String? relativePath,
}) => L10nEvidenceFailure(
  code: code,
  stage: stage,
  detailCode: detailCode,
  relativePath: relativePath,
);

bool _sameStrings(Iterable<String> left, Iterable<String> right) {
  final leftSet = left.toSet();
  final rightSet = right.toSet();
  return leftSet.length == rightSet.length && leftSet.containsAll(rightSet);
}

void _validateMode(int? value, String name) {
  if (value != null && (value < 0 || value > 0xfff)) {
    throw ArgumentError.value(value, name);
  }
}

bool _isSafeRelativePosixPath(String value) {
  if (value.isEmpty ||
      value.startsWith('/') ||
      value.endsWith('/') ||
      value.contains('\\') ||
      value.contains(':') ||
      value.contains('%') ||
      value.contains('?') ||
      value.contains('#') ||
      value.codeUnits.any((unit) => unit < 0x20 || unit > 0x7e)) {
    return false;
  }
  return value
      .split('/')
      .every(
        (segment) =>
            segment.isNotEmpty &&
            segment != '.' &&
            segment != '..' &&
            RegExp(r'^[A-Za-z0-9._-]+$').hasMatch(segment),
      );
}

String _asciiFold(String value) => String.fromCharCodes(
  value.codeUnits.map(
    (unit) => unit >= 0x41 && unit <= 0x5a ? unit + 0x20 : unit,
  ),
);
